# ######################################################################################################################
# Sample Cloudformation Transform Lambda Function
# Version: 1.0
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# Creates a AWS lambda that will be used by an AWS Cloudformation transform.
#
# #######################################################################################################################
Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
  LambdaHandlerPath:
    Type: String
    Description: Path of a Lambda Handler.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value:
      Fn::GetAtt:
        - LambdaRole
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaRole
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value:
      Fn::GetAtt:
        - LambdaFunction
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaARN-${EnvName}
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: /
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: macro-lambda-${EnvName}
      Description: LambdaFunctioni of nodejs12.x.
      Runtime: nodejs12.x
      Code:
        ZipFile:
          "def lambda_handler(event, context):\n
            fragment = event['fragment']\n
            event_type = event['params']['FleetType']\n
            team_size = int(event['params']['InputSize'])\n
            print(fragment)\n
            if event_type == 'task':\n
              if fragment['Properties']['TargetOnDemandCapacity'] == 'custom::Target':\n
                fragment['Properties']['TargetOnDemandCapacity'] = team_size\n
              elif fragment['Properties']['TargetSpotCapacity'] == 'custom::Target':\n
                fragment['Properties']['TargetSpotCapacity'] = team_size\n
            print(fragment)\n
            return {\n
            'requestId': event['requestId'],\n
            'status': 'success',\n
            'statusCode': 200,\n
            'fragment': fragment\n
            }"
      Handler: ${LambdaHandlerPath}
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Environment:
        Variables:
          ENV:
            Fn::Sub: ${EnvName}

